### ISSUE TITLE
Edit manager sentry modal

### ISSUE THREAD

**Issue by ThomasJuster** [France-ioi/AlgoreaFrontend#1025]
**Describe the bug**
A Sentry modal is opened

**To Reproduce**
1. Go to [this page](https://dev.algorea.org/en/#/groups/by-id/3179835668434339048;path=5121055722873780306/details/managers) as usual user
2. Click on 'Edit manager'
3. See the sentry modal (under our own modalm which might by the way be another bug)

**Expected behavior**
No Sentry modal should appear. There shouldn't even be a bug here, we're just opening a modal

**Comment by smadbe** [comment]
What is "edit manager", the pen icon? I do not have sentry modal show up in this case. 
But I agree that is problematic.
