### ISSUE TITLE
Item details: children (part 1)

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#107]
# Objective
Display children as shown [here](https://france-ioi.github.io/algorea-designs/03.Activities_01.Content_a.Content-presentation-(full-text)).

# Details
* Do a separate component which is only visible for chapters (item.type 'Chapter') and with can_view >= content
* Add the "To validate this chapter, solve at least all tasks with Validation type " with the same style as designs
* Use the usual loading/error/ready state for fetching children data (https://france-ioi.github.io/algorea-devdoc/api/#operation/itemChildrenView)
* just display the "ready"  string when the data is loaded, we'll do the display in another issue

**Comment by GabrielVidal1** [comment]
done in #127
