### ISSUE TITLE
"activeTab is undefined" error

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#1085]
**Describe the bug**
From time to time, I get this "activeTab is undefined" error in the console with no stack trace and no idea how it appears. From what I see there is only one place where an `activeTab` variable is used: `left-nav.component.html`, so probably finding the root cause should not be too complex.

![Screenshot 2022-07-01 at 18 08 07](https://user-images.githubusercontent.com/1053150/176931023-de9c7b53-e10d-411f-8b0c-a2b53bfae26a.png)

**Comment by ThomasJuster** [comment]
The only mentions to `activeTab` are all located indeed in `left-nav.component.html`
However, the first line of this file is the following:
```html
<ng-container *ngIf="activeTab$ | async as activeTab;">
```
Due to Angular's template engine, it should be impossible for `activeTab` to be `undefined` :shrug:

**Comment by smadbe** [comment]
I haven't seen this problem for a while, it has probably been fixed somehow.
