### ISSUE TITLE
Get rid ng-click-outside lib and create custom directive

### ISSUE THREAD

**Issue by Iloveall** [France-ioi/AlgoreaFrontend#1103]
## Overview
The ng-click-outside lib has been deprecated

https://www.npmjs.com/package/ng-click-outside

As result of angular update to v14, on build step I've got the error:

<img width="915" alt="Screenshot at Jul 19 17-18-12" src="https://user-images.githubusercontent.com/7044736/179775802-7b15c0ee-24f8-4c1f-a37a-91570a5612f6.png">

## Acceptance criteria
- [ ] Remove ng-click-outside
- [ ] Create custom directive (based on similar [logic](https://github.com/France-ioi/AlgoreaFrontend/pull/1097/files#diff-175faef3bf417f5b0f60765144f5394fad2be06ac2f4bbcae263dd9bfa693f8f))
- [ ] Change ng-click-outside with new directive in select component

**Comment by Iloveall** [comment]
I’ve found that the directive click-outside used only in SelectComponent component. But SelectComponent not used in app. So mb need to remove both? Otherwise there are no case even for test click-outside directive

**Comment by smadbe** [comment]
Yes, of course, just remove both !
