### ISSUE TITLE
Fix style of search boxes

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#1145]
**Describe the bug**

When reducing the size of the screen, we go from: 
![Screenshot 2022-09-21 at 17 08 16](https://user-images.githubusercontent.com/1053150/191541394-3e548624-39c7-49c0-a9b7-cdaf40fc8cff.png) (good)

to
![Screenshot 2022-09-21 at 17 08 29](https://user-images.githubusercontent.com/1053150/191541438-9128b843-24bc-4b12-8d05-0aa4c9c737cc.png) (not good)

... while the width is still decent-enough for a desktop browser.

**To Reproduce**
1. As the usual user
2. I visit https://dev.algorea.org/en/activities/by-id/4728890134807328169;path=5846722634000078615;attempId=0/details/dependencies
3. I decrease the width of the window

**Comment by Iloveall** [comment]
It's old design, so now the problem fixed
