### ISSUE TITLE
Item progress tab: log view (first version)

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#124]
# Overview 

In the progress page (for instance http://dev.algorea.org/en/#/activities/by-id/4702;parentAttempId=0;path=/details/progress), display a list (table) of latest activities of the current user on this item. (as bit as drafted at the bottom of [this design](https://france-ioi.github.io/algorea-designs/02.Skills_02.Progression) , but with more relevant content)

# Details
* In ItemLogViewComponent (existing component):
   -  add a table to display the result of `state.data` (check MemberListComponent for an example of table)
   - this table should have the following columns:
      * "Action", which values which could be (see ([API for the service](https://france-ioi.github.io/algorea-devdoc/api/#operation/itemActivityLogForItem) for explanation of the input) "Submission" (if "submission" with score undefined), "Submission (score: <score>)" (if "submission" with score given), "Activity started" (if "result_started") or "Activity validated" (if "result_validated")
      * "Content", which is the "title" of the item with a link to that item
      * Time with minute precision  (check MemberListComponent for an example)
* May require to update a bit the `ActivityLog` interface returned by the service. ([API for the service](https://france-ioi.github.io/algorea-devdoc/api/#operation/itemActivityLogForItem) used)
* No need to support any sort for now.

**Comment by smadbe** [comment]
Note that item-log-view component should probably be included in item-current-situation component by routing.

**Comment by smadbe** [comment]
It would be nice to create a PR when you have the structure of the components so that other devs can start on the tabs in parallel.

So the PRs should be: 
1) the pages structure with a simple message
2) the page which may be in error, loading or ready state, on ready state (data loaded), just display "data loaded"
3) the data is displayed as expected

**Comment by mblockelet** [comment]
Hi, sorry again for the delay, I should be working on it either tonight if I feel well enough, or tomorrow. Sure for the three pull requests.

**Comment by smadbe** [comment]
The service has been completely reworked to match the most recent needs, see https://france-ioi.github.io/algorea-devdoc/api/#operation/itemActivityLog. 
As I also mentioned somewhere else, I have (before the new service) re-written most of your component to match changes related with routing and the clean things that I missed during the review.
The third and last PR on this issue should then be to adapt the service and to display the expected data in the table.

**Comment by smadbe** [comment]
Description rewritten.
