### ISSUE TITLE
Fix add content widget for mobile

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#1249]
## Overview
Fix add content widget for mobile

## Acceptance criteria
![Screenshot 2022-12-22 at 16 41 57](https://user-images.githubusercontent.com/1053150/209170211-d388d7f8-c099-4622-8cd8-45de2f1d3e28.png)
- [ ] fix how it is displayed

**Comment by Iloveall** [comment]
Couldn't reproduce it

**Comment by smadbe** [comment]
Tested on firefox mobile and on chrome by @Iloveall . Only happening on my desktop firefox ?
