### ISSUE TITLE
Convert button to <a> with button shapes

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#1313]
## Overview
As discussed on slack around 1/03/23, for buttons with `routerLink`, we should use a `<a>` tag so that we can the link can be displayed by the browser.

## Acceptance criteria
- [ ] Transform `<button pButton ...`  to `<a pButton ...` everywhere we use a routerLink
- [ ] Make sure the styles are not broken

**Comment by Iloveall** [comment]
`<li>` - breadcrumbs.component
`<span>` - left-nav-tree.component
`<button>` - neighbor-widget.component
`<button>` - page-navigator.component
`<div>` - parent-skills.component
`<div>` - chapter-children.component
`<span>` - group-progress-grid.component
`<div>` - item-children-list.component

**Comment by Iloveall** [comment]
Requires to merge [PR](https://github.com/France-ioi/AlgoreaFrontend/pull/1310)
