### ISSUE TITLE
Get rid of the @fortawesome icons

### ISSUE THREAD

**Issue by Iloveall** [France-ioi/AlgoreaFrontend#1409]
## Overview

As we are using @phosphor-icons once (probably after full redesign) we need to get rid of the @fortawesome package

## Acceptance criteria
- [ ] Remove npm packages
- [ ] Replace with @phosphor-icons if needed

**Comment by smadbe** [comment]
Shouldn't we wait for all pages (groups, ...) to be converted before removing the package?
