### ISSUE TITLE
Show search result hightlights

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#1419]
## Overview

Add the highlights in search results
![Screenshot 2023-06-28 at 17 04 50](https://github.com/France-ioi/AlgoreaFrontend/assets/1053150/e8b59619-3620-4d33-832d-16e8aa53a7b7)

##  Search service update

The search service now returns in the result tuple (next to type, score):
  * `title_highlight: string|null`
  * `highlights: string[]` (may be empty, max 3)

The highlight strings are max-100-char text extracts of the content which match the query. The matching part is surrounded by `<em></em>` html tags. (if you want me to add a specific `class` to the `em`, let me know)

## Acceptance criteria
- [ ] if there are `highlights`, display them as shown in the design (with the `em` part blue-highlighted)
- [ ] if `title_highlight` is not null display the `em` part blue-highlighted in the search result title

**Comment by Iloveall** [comment]
Please add some `alg-class` to the `em`

**Comment by smadbe** [comment]
as discussed on slack, let's try to do it with css class hierarchy instead.
