### ISSUE TITLE
New Design: Message component

### ISSUE THREAD

**Issue by Iloveall** [France-ioi/AlgoreaFrontend#1624]
## Overview

Improve design for message component.

Should we adjust this one component or get rid of it and to use toast notifier?

<img width="893" alt="message-ui" src="https://github.com/France-ioi/AlgoreaFrontend/assets/7044736/895748ed-068f-41aa-8d42-7f7aba7b39a6">
<img width="1039" alt="message-ui2" src="https://github.com/France-ioi/AlgoreaFrontend/assets/7044736/bf2db78f-b8de-45fb-acf4-4650067ca93d">

## Acceptance criteria
- [ ] Change bg color
- [ ] Adjust space
- [ ] Adjust fonts
- [ ] Change icons

**Comment by smadbe** [comment]
> Should we adjust this one component or get rid of it and to use toast notifier?

I think that's ok to use the messages as they are (not using the `ActionFeedbackService`) for now. That allows to copy/paste/fix more easily in the case of many logins than the toast which would disappear on click.
