### ISSUE TITLE
New Design: Chapter no visible content

### ISSUE THREAD

**Issue by Iloveall** [France-ioi/AlgoreaFrontend#1680]
## Overview

Change design for chapter no visible content message

<img width="700" alt="chapter_no_visible_content" src="https://github.com/France-ioi/AlgoreaFrontend/assets/7044736/a22e0a9d-9d2c-49ed-a5f6-30186b5472f4">

## Acceptance criteria
- [ ] Replace with regular error component
- [ ] Add icon (?)

**Comment by smadbe** [comment]
>  Add icon (?)

If you do not find better, you can just use a folder icon :-/
