### ISSUE TITLE
API change: `invitationView`: `inviting_user` may be null

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#1745]
The API changes to reflect a case that may happen: 

In the [invitationView](https://franceioi-algorea.s3.eu-west-3.amazonaws.com/spec/v2.21.3.html#tag/group-memberships/operation/invitationsView) service, `inviting_user` is nullable. Update the frontend to handle that case.

**Comment by Iloveall** [comment]
It seems already done https://github.com/France-ioi/AlgoreaFrontend/commit/1f9b6824687a738dd27bb48d468e685d94e9eb54#diff-e7359aa278dafd6fe6298d7d7004621fb3038c97304979caf2fa574485e5db78R35
