### ISSUE TITLE
Task integration : backend communication

### ISSUE THREAD

**Issue by mblockelet** [France-ioi/AlgoreaFrontend#177]
# Overview

This issue pertains to the communication between the frontend and the backend to make task integration work with real data.

Depends on : #176 and other aspects around items (result / attempt management, ...).

# Subtasks

- [ ] Use actual item URL and get tokens
- [ ] Load current answer / save new answer
- [ ] Save grades

**Comment by smadbe** [comment]
completed by Thomas in other issues
