### ISSUE TITLE
Children of Item still displayed as loading after cancelling the loading

### ISSUE THREAD

**Issue by AyeRlS** [France-ioi/AlgoreaFrontend#285]
Step to reproduce : 
- Be in edition mode of an item
- Make some changes
- Click on another item on the left menu
- Don't save your change and stay on the current item

You will still see the spinner for the item you've clicked, as if it was still loading

**Comment by smadbe** [comment]
We can try to fix this either by listing to the navigate event (it is a JS promise, maybe it receives an event when the nav is cancelled), or by adding a "timeout" on the spinner so that it stops spinning after 5sec anyway, or another smarter solution.

**Comment by smadbe** [comment]
Cannot happen anymore.
