### ISSUE TITLE
Refresh user session when profile data is updated

### ISSUE THREAD

**Issue by ThomasJuster** [France-ioi/AlgoreaFrontend#422]
## Motivations

The user session should be refreshed  when updating user data.

## Subtasks

* In the current-user service, add a refresh subject to trigger on user update
* In the user-session service, observe the current user refresh subject to refetch user info

**Comment by smadbe** [comment]
Current-user service is an http service. These http services are typically stateless. So the subject should probably just be in user session.

**Comment by ThomasJuster** [comment]
## New Subtasks

* In the user-session service, add an internal/private refresh subject
* In the user-session service, add a method `updateCurrentUser()` calling current user service and feed internal refresh.
* Fix typing of current-user service for `update()` method
* Refactor current-user component to use user-session service instead of current-user service

**Comment by smadbe** [comment]
👍
