### ISSUE TITLE
Assert platform language at app initialisation

### ISSUE THREAD

**Issue by ThomasJuster** [France-ioi/AlgoreaFrontend#424]
## Motivations

The platform language should be known. If the language is not provided or if it is not among the available ones, we should display an error preventing access to the app and asking to pick an available language.

## Subtasks

* In the configuration, mark languages as required
* In locale service, mark platform language and languages as required
* On initialisation, assert that platform language is defined (which also means it exists among the configuration languages)
* In the app component, if the platform language is not defined, display a configuration error blocking the UI

**Comment by smadbe** [comment]
> On initialisation, assert that current language is defined and exists
> In the app component, if the platform language is undefined, display a blocking message "No language is selected, please pick one:" and a language picker

platform language ><  current language ?

If we cannot find the current language among the configured language, we should block the UI saying there is configuration error. I don't think there a need for any language picker in this issue.


In the app component, if the platform language is unknown, display a blocking message "This language [lng] is not supported by the platform, please pick one:" and a language picker

**Comment by ThomasJuster** [comment]
## New Subtasks

* In the configuration, mark languages as required
* In locale service, mark current language and languages as required
* On initialisation, assert that platform language is defined and exists
* In the app component, if the platform language is not defined or is not among accepted languages, display a configuration error blocking UI.

**Comment by smadbe** [comment]
I am not sure I get "platform language is not defined or is not among accepted languages". The way to find what the current language is to find the path among the language in config. So finding the language is by definition and accepted language. Am I wrong?

**Comment by ThomasJuster** [comment]
right, I'm left only with the undefined possibility

**Comment by ThomasJuster** [comment]
## Subtasks

* In the configuration, mark languages as required
* In locale service, mark platform language and languages as required
* On initialisation, assert that platform language is defined (which also means it exists among the configuration languages)
* In the app component, if the platform language is not defined, display a configuration error blocking the UI

**Comment by ThomasJuster** [comment]
Sure, I think we can repeat this process for next times: suggesting motivation or subtasks in comments, and when reviewed edit the main description.
