### ISSUE TITLE
Provide platform language when creating a temporary user

### ISSUE THREAD

**Issue by ThomasJuster** [France-ioi/AlgoreaFrontend#425]
## Motivations

Currently, temporary users are created using `fr` as default language. This will be problematic when we will handle current user language not matching the platform language. For temporary users (any unregistered visitor), whenever the platform will be launched in English, there will always be a dialog prompting that the language doesn't match even before they could pick one.

## Subtasks

* Update the auth http service method `createTempUser` to accept `default_language`
* In the auth service, access the locale service to retrieve the platform language, use it to create temporary users: in the constructor and when the token is invalid.

**Comment by smadbe** [comment]
Implemented and deployed in backend: https://france-ioi.github.io/algorea-devdoc/api/#operation/tempUserCreate
