### ISSUE TITLE
Bug in user formatting 

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#452]
User formatting does not work correctly in multiple places: 
![Screenshot 2021-06-01 at 10 58 58](https://user-images.githubusercontent.com/1053150/120296413-62193900-c2c8-11eb-822d-22df4a9c500f.png)
![Screenshot 2021-06-01 at 11 02 25](https://user-images.githubusercontent.com/1053150/120296879-db189080-c2c8-11eb-8901-69cbf62257b4.png)

- probably because they are undefined while your pipe do not handle `undefined`.
- because the list of members use `let-rowData` which returns a `any` 😡. Would you have a proposal to get the types for the table rows?
- UserDescendant (and probably similar services) assumes first/lastnames cannot be `undefined` while they may. So fix them. (and maybe use the decoder instead)

**Comment by Iloveall** [comment]
It can't be my pipe as it not merged yet, so need to merge at first this one PR https://github.com/France-ioi/AlgoreaFrontend/pull/427

Then my offer is to merge UserPipe (old) and userCaption (new), but there is also formatUser helper which is the function for formatting (with undefined issue) and which uses in other places directly.
