### ISSUE TITLE
Remove the "Course" type

### ISSUE THREAD

**Issue by mblockelet** [France-ioi/AlgoreaFrontend#544]
## Overview
Remove the "course" type. All courses have been converted to tasks in the db.

## Acceptance criteria
- [ ] Make sure the "course" type does not appear anywhere as item type or in the app texts
- [ ] Make sure a new item cannot be created with a type "course" (the selector)

# Initial discussion

An item can currently be of the types Chapter, Task, Course, Skill. However, the Course type is not very useful, as it's basically an ungraded Task :

* same display as a Task (URL embedded in an iframe)
* most implement bebras API (mainly to return display height)

But with some differences :

* no score
* no state/answer
* different icon
* single attempt
* ... (other ones?)

Moreover, the name "Course" can be confusing, as we now have "courses" which are graded (for instance, YouTube videos which give you a grade depending on how many sections were visited). It would also help development to have only the type "Task" to care about, rather than having conditions "type is Task or Course" everywhere, to only end up having very few differences between both.

Those differences might be better expressed as existing attributes of the item (noScore, allowsMultipleAttempts), or new attributes (icon).

Thus it could be useful to just remove the "Course" type, and add attributes if needed.

**Comment by smadbe** [comment]
* Does it mean we have to pass all existing (203) courses to "no score" ?  (none is 'no score' for now)
* For "no state/answer", what should we do in practice? Intuitively, I feel like it should not be a property stored in the backend but rather task itself (in its iframe) responding differently (or not responding at all) to some calls.

**Comment by mblockelet** [comment]
* All existing courses should be put to "no score" indeed.
* These "courses" have a special behavior for state/answer : state is always an empty string, answer is an empty string initially and, in the general case, a string 'page_read' after a few seconds, as it is used by some platforms to detect activity on the task. We don't necessarily need to do anything in practice on the platform-side for such tasks.
