### ISSUE TITLE
Complete basic task integration

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#628]
Take over the task integration started by Michel:
- probably discuss with Damien to have a first introduction
- quickly have a look at https://france-ioi.github.io/algorea-devdoc/task_platforms/token/
- have a look at https://github.com/France-ioi/AlgoreaFrontend/pull/474/files
- do the review of https://github.com/France-ioi/AlgoreaFrontend/pull/620 (with my changes directly)
- implement https://github.com/France-ioi/AlgoreaFrontend/pull/620#discussion_r693739758
- review in details #526
- check if it can be merged like that for a initial version in your opinion (then we'll discuss with Michel and Mathias if that's ok)

**Comment by ThomasJuster** [comment]
Missing platform functions:
- `askHint`
- `log`
