### ISSUE TITLE
Item task: auto activate full frame mode

### ISSUE THREAD

**Issue by ThomasJuster** [France-ioi/AlgoreaFrontend#729]
## Motivation

To enhance user experience, when displaying a task we should focus on the task − thus enter automatically “full frame” mode. 
“full frame” mode means the left menu is collapsed.

~However, when the user manually expands the left menu, we should disable that behavior for 2 hours, unless the user manually re-collapses the left menu.~

Fixing this issue will allow to delete [this branch](https://github.com/France-ioi/AlgoreaFrontend/compare/item-display-2?expand=1)

## Acceptance criteria (update 1/11, post discussion with Mathias)

- [x] 
  * When navigating to a task, **not using** the left nav for navigation
  * Then, the left menu collapses (if not already)
- [x] 
  * When navigating to a task, **using** the left nav for navigation
  * Then, the left menu stays visible
- [x] 
  * When navigating to a non-task (chapter, skill, group, ...) from a task 
  * Then, the left menu expends (if not already)
- [x] 
  * When navigating to a non-task (chapter, skill, group, ...) from a non-task 
  * Then, the left menu stays as it was
- [x] 
  * When using the collapse/expend button on the top of the left menu
  * Then, the left menu collapses/expends as expected

<details>
<summary>
Former acceptance criteria
</summary>

- [x] When:
- navigating to a chapter, a skill or a group

:arrow_right: full frame should not be activated
&nbsp;
- [x] When:
- navigating to a task

:arrow_right: full frame should be activated at task initialisation
&nbsp;
- [x] When:
- visiting a task
- expanding left menu manually
- visiting another task

:arrow_right: full frame should not be activated. This behavior should last 2 hours (add an escape hatch to test it on the branch)
&nbsp;
- [x] When:
- visiting a task
- expanding left menu manually
- collapsing left menu manually
- visiting another task

:arrow_right: full frame should remain activated
&nbsp;
- [ ] When:
- visiting a task
- navigate to a chapter
- expanding left menu manually
- visiting a task

:arrow_right: full frame should be activated at the (first and) last task initialisation
&nbsp;
</details>

**Comment by ThomasJuster** [comment]
The acceptance criteria mention task and non-task items, what about courses ?
Currently, both task and courses are displayed in iframes, my primary thinking would be that courses too are concerned by the change.

**Comment by smadbe** [comment]
"Courses" are supposed to be merged with "Tasks" anytime soon. So it should behave like tasks.
