### ISSUE TITLE
item task auto save: on error, retry

### ISSUE THREAD

**Issue by ThomasJuster** [France-ioi/AlgoreaFrontend#736]
## Actual

When starting a task, if auto save fails, a message `Unable to load task` is printed. The behavior is incorrect because it can happen anytime after the task is started, for instance when the user loses (temporarily or not) internet connection

## Expected

- [ ] each time a state/answer has to be saved, retry on error every 15sec, forever 
- [ ] make sure that previous saves and their retries are cancelled before trying a new one

**Comment by smadbe** [comment]
Should be done implicitly by #776
