### ISSUE TITLE
Remove invalid `action` tolerance in group member service decoder

### ISSUE THREAD

**Issue by ThomasJuster** [France-ioi/AlgoreaFrontend#757]
On [this group](https://dev.algorea.org/en/#/groups/by-id/672913018859223173;path=52767158366271444/details/members), the group member service returns member list items containing `action: ""`, which is not a valid value according the [backend OpenAPI specification](https://france-ioi.github.io/algorea-devdoc/api/#operation/groupsMembersView).

As of today, we tolerate values containing `action: ""` not to break UI.

When the backend service is fixed (see https://github.com/France-ioi/AlgoreaBackend/issues/798), remove this tolerance

**Comment by smadbe** [comment]
Included in #870
