### ISSUE TITLE
In item chapter: success scores are partially displayed

### ISSUE THREAD

**Issue by ThomasJuster** [France-ioi/AlgoreaFrontend#791]
**Describe the bug**
In a chapter, for some validated items the score is partially displayed: there's an **empty** green circle

**To Reproduce**
1. Go to [this chapter](https://dev.algorea.org/en/#/activities/by-id/34689573454313988;path=4702,1352246428241737349,314613032161178344;attempId=0/details) as usual user
2. See first and last chapter items

**Expected behavior**
Either the score or a tickbox should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/16257159/138661776-9ba6eec3-3173-42e0-95fd-102677f08623.png)

**Comment by smadbe** [comment]
Covered by #804
