### ISSUE TITLE
Implement task `askHint` platform function

### ISSUE THREAD

**Issue by ThomasJuster** [France-ioi/AlgoreaFrontend#800]
## Overview

Some tasks provide the ability to ask hint(s). For technical details, refer to [this documentation](https://france-ioi.github.io/algorea-devdoc/task_platforms/token/#hint-request)

## Acceptance criteria

This platform function can be tested on [this task](https://dev.algorea.org/en/#/activities/by-id/773396873861865944;path=4702,1625159049301502151;parentAttempId=0/details)

- [ ] After requesting a hint, the task should display the hint
- [ ] If an error occurs, display a toast mentioning that the hint request failed (toast is not persistent).

**Comment by smadbe** [comment]
Note about priority: quite low, mainly used in Alkindi.
