### ISSUE TITLE
Handle item requiring explicit entry

### ISSUE THREAD

**Issue by ThomasJuster** [France-ioi/AlgoreaFrontend#860]
HEAD NOTE: this issue will be split into multiple ones later.
Other documentation: https://france-ioi.github.io/algorea-devdoc/items/contests/

# Overview

When visiting an item _with no explicit entry_, the last attempt is retrieved and if none exists, one is created.
When visiting an item _with ~no~ explicit entry_, the last attempt is retrieved and if none exists, **none is created** because the item must be started (an attempt must be created) manually by the user.

(From now when you read "item", read "item _with explicit entry_")

### Changes to the item page

When an item is not started, we can check the entry state of the item (<> can the user enter/start or not) using [get entry state](https://france-ioi.github.io/algorea-devdoc/api/#operation/itemGetEntryState) backend service.

For now, when `entry_participant_type === 'Team'`, we will refuse the entry because it implies to take other parameters into account like `entry_min_admitted_members_ratio` and so on ; it will be done later.

#### `item.permissions.canView >= 'content'`
Nothing to do, display the item as usual. Under the hood, it means that the user has already "started" the activity

#### `item.permissions.canView === 'none'
Nothing to do, display the usual message "You have not access to this item …"

#### `item.permissions.canView === 'info'`

Display a section with a "Start" button, the duration if there's one and the max attempts if `allow_multiple_attempts === true`. When the start button is clicked, create an attempt and refetch item & its children. Creating the attempt will set the `item.permissions.canView` to a value >= "content".

There will be additional info to display base on the values of `can_enter_(from|until)` and `entering_time_(min|max)` :construction: 

### Changes to the item form

In "Advanced parameters", add a new select field `entry_min_admitted_members_ratio` with options `['None', 'All']`
It should visible even when `entry_participant_type === 'User'` because a user is a group of 1.

For design information, browse through "activities-skills > header > team registration" which is the most resembling screen (link to come :construction:)

### Tests

1) I am a student (I have not created the item, I'm not owner…), I have to click "Start" to enter.
- Test with `duration` & no `duration`
- Test with `entering_time_(min|max)` & no `entering_time_*`

2) I created the item, I am admin (owner of the item), I'm not concerned by the `entering_time_(min|max)` nor the `duration`
- Test with an attempt.

**Comment by smadbe** [comment]
done in #1758
