### ISSUE TITLE
UI improvement: on item form: cancel and delete buttons may overlap

### ISSUE THREAD

**Issue by ThomasJuster** [France-ioi/AlgoreaFrontend#899]
**Describe the bug**
Cf title

**To Reproduce**
1. As usual user, go to [this item form](https://dev.algorea.org/en/#/activities/by-id/6010615591035594227;path=4702,1625159049301502151;parentAttempId=0/edit/advanced-parameters)
2. Scroll down to the bottom of the page

**Expected behavior**

There should padding at the bottom of the page to give room to fixed buttons "Save" and "Cancel changes"

**Screenshots**
![image](https://user-images.githubusercontent.com/16257159/153021770-6fa3030a-bcbd-4e80-8559-161aaeaab983.png)

**Comment by smadbe** [comment]
The delete buttons should now have been moved to the left.
