### ISSUE TITLE
Fix static common asset serving: tree-folder image not included as it should

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#905]
**Describe the bug**

The `tree-folder.svg` image, used in the left menu seems not to be included as it should.
As a consequence, it is not served and packed as the other assets and it causes me other deployment issues.

**Screenshots**
![Screenshot 2022-02-09 at 18 22 11](https://user-images.githubusercontent.com/1053150/153255300-d41ee2d7-cdf8-4561-8c38-58d4c9b79f2f.png)

**Comment by Iloveall** [comment]
I’ve found info that --deploy-url  doesn’t change src for images. So I guess we need to approve another approach
