### ISSUE TITLE
Do not display "expected" 404/403 in the console

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#907]
## Overview
Currently, we have a few services which receive "expected" 404 or 403 http status code, for instance the once fetching the current answer returning 403 if there is no current answer yet.

[Example as unauthenticated user.](https://dev.algorea.org/en/#/activities/by-id/6314563572459051248)

The "problem" is that these end up in the console as an error which may be interpreted by customers as bugs or auto notified in bug collectors.
![Screenshot 2022-02-09 at 18 35 10](https://user-images.githubusercontent.com/1053150/153257510-31bdc34a-3221-4c3d-8139-64668cafd559.png)

Try to catch it before it reaches the console (using `preventDefault`?).

## Acceptance criteria
- [ ] Catch expected 404/403 so that it does not reach the browser console anymore.
- [ ] Make sure the unexpected errors still reach the console. 

## Notes

If the solution may be worth a discussion before implementing, let's discuss it before modify the code!

**Comment by ThomasJuster** [comment]
I don't think we can do anything about that, and if we do it will be a horrible tinkering.
https://stackoverflow.com/questions/22113286/prevent-http-errors-from-being-logged-in-browser-console
https://stackoverflow.com/questions/4500741/suppress-chrome-failed-to-load-resource-messages-in-console

**Comment by smadbe** [comment]
Ok. We'll do required changes in the backend then. 🤷‍♂️
Keep us posted if you see another good solution.
