### ISSUE TITLE
Allow tasks to disable "progress" tab

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#919]
## Overview
Some tasks may request not to show the progress tab when not in observation (to prevent polluting with this tab, to prevent previous submission loading or to handle these themselves).

## Acceptance criteria
- [ ] support `disablePlatformProgress` in `ask.getMetaData`. If given and `true`, do not show the progress tab when not in observation mode.
- [ ] this task: https://tasks.algorea.org/?taskId=145659473473003296 and globally all tasks on `tasks.algorea.org` have it "true".
- [ ] other tasks should not be broken
- [ ] in observation mode, the tab should be shown anyway
- [ ] if they is only one tab at the end (the "content" one), hide the tab bar

**Comment by ThomasJuster** [comment]
What is supposed to happen when we land directly on the progress page ?

**Comment by smadbe** [comment]
The easiest for you. You can display it the progress tab with it For now, the goal is just to "hide the complexity" to the user. If we want to really prevent the user from loading former submission, we would need to block this at the task level anyway.
