### ISSUE TITLE
Hide task loading in favor of app loading

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#945]
## Overview
We display a loading spinner while a task is not loaded yet, but some tasks have their own spinner as well. As a result, we may end up with double spinner such as: 
![image(1)](https://user-images.githubusercontent.com/1053150/155141214-aa214b15-56e8-4e67-9a25-94a3f2730a85.png)

Let's "hide" the task while it does not declare itself as loaded.

## Acceptance criteria
- [ ] Make our "loading spinner layer" opaque and displayed over the task iframe so that the task is hidden while loading
- [ ] When the task is loaded, remove our "loading spinner layer" and show the task

**Comment by ThomasJuster** [comment]
Link to the task: https://dev.algorea.org/en/#/activities/by-id/8148962848812891795;path=4702,458602124916982205,4769434107088212490,8123435593727593341,5072731755477071719,8600972556668887052;parentAttempId=0/details
