### ISSUE TITLE
Use p-button instead of alg-button

### ISSUE THREAD

**Issue by Iloveall** [France-ioi/AlgoreaFrontend#961]
## Overview

I haven't found used secondary and warning buttons.

## Acceptance criteria
- [ ]

1. Clarify buttons scss file, remove unused code

**Comment by smadbe** [comment]
Is there still a need for a custom "button" over the primeng button ?

**Comment by Iloveall** [comment]
alg-button component has wrapper of button scss styles, so yes. In some cases we are using directly <p-button> in other cases custom alg-button. But I don't see different, alg-button is just wrapper for <p-button>, so I would suggest to clarify approach and mb get rid alg-button, change it to <p-button>

**Comment by smadbe** [comment]
>  I would suggest to clarify approach and mb get rid alg-button, change it to <p-button>

I agree
