### ISSUE TITLE
Bug on task tab change handling

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#965]
**Describe the bug**
Various small bugs in tasks when tabs are removed/added depending on the size of the screen.

**To Reproduce**
1. As any user
2. I visit [this task](https://dev.algorea.org/en/#/activities/by-id/6010615591035594227;path=4702,1625159049301502151;attempId=0/details).
3. I see 3 tabs: statement, hints, solve. If not zoom so that you have 3 tabs.
4. I select the "solve" tab
5. Zoom out so that you have "statement" and "solve" merged in a single tab (so 2 tabs in total)
6. No tab is selected any while you are clearly in the "statement" tab **(bug 1)**
7. Zoom in so that you see 3 tabs in total
8. The "solve" tab is enabled while the content below is the content from the "statement" tab. **(bug 2)**

**Comment by ThomasJuster** [comment]
What's the expected behavior ?

**Comment by smadbe** [comment]
6+8. Have the tab corresponding to what's displayed selected. 🤷‍♂️
