### ISSUE TITLE
Handle correctly loading

### ISSUE THREAD

**Issue by AyeRlS** [France-ioi/AlgoreaFrontend#98]
When loading something, if the user input something else, the website can find itself in a "loaded" state when it is in fact not.

For exemple : you can have a "change" to "B" during the loading of "A", so you should not put "A" as "loaded", but instead wait for "B" to be loaded.

**Comment by smadbe** [comment]
Could you add more details on a precise case. Otherwise, we'll not be able to understand what it means in practice. You can use a specific case in example.

**Comment by smadbe** [comment]
In what screen more precisely? Can you give a precise example?

**Comment by smadbe** [comment]
I cannot reproduce or don't understand or it has been fixed.
