### ISSUE TITLE
Fix unhandled http error: POST answer 

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#994]
## Overview

Error received in Sentry:

```json
{"error":{"currentTarget":"[object Null]","isTrusted":true,"target":"[object XMLHttpRequest]","type":"abort"},"headers":{"headers":"[Object]","lazyUpdate":null,"normalizedNames":"[Object]"},"message":"Http failure response for https://dev.algorea.org/api/answers: 0 Unknown Error","name":"HttpErrorResponse","ok":false,"status":0,"statusText":"Unknown Error","url":"https://dev.algorea.org/api/answers"}
```

HTTP Status code 0 🙄

From page: /activities/by-id/2377619260689967292;path=4702,458602124916982205,4769434107088212490,8123435593727593341,5072731755477071719,8600972556668887052;parentAttempId=0/details

**Comment by ThomasJuster** [comment]
I found some documentation for that 0 status code: https://stackoverflow.com/questions/872206/what-does-it-mean-when-an-http-request-returns-status-code-0
From what I see of error, there's also a `type: abort` which is _probably_ responsible for the 0 status code.

That being said, there is still – apparently – an unhandled error which I'll deal with.
